/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 * hey.
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <stdlib.h>
/*#include <string>
using namespace std;*/
#include "subagents.h"

//using namespace std;
#define MAX_STR_LEN 256
/*---------------------------------------------------------------------------------------------------*/

/* Make sure those next includes files are at this path, and that you've got the files */

#include "hiredis/hiredis.h"
#include "hiredis/async.h"
#include "hiredis/adapters/libevent.h"

/*---------------------------------------------------------------------------------------------------*/
//Redis connection
static redisContext *c;
redisContext **con = &c;

/*-----------------------------------------------------------------------------------*/
/*                                                                                   */
/* Every commented "DEBUGMSGTL" had exchanged with snmp_log, it's a way of debugging */
/*                                                                                   */
/*-----------------------------------------------------------------------------------*/

